name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  setup:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ./packages/web-components/node_modules
          key: ${{ runner.os }}-modules
      - run: cd ./packages/web-components && npm ci
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: cd ./packages/web-components && npm run build.stencil
  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/cache/restore@v3
        id: cached-deps-on-e2e
        with:
          path: ./packages/web-components/node_modules
          key: ${{ runner.os }}-modules
      - name: Install dependencies
        if: steps.cached-deps-on-e2e.outputs.cache-hit != 'true'
        run: cd ./packages/web-components && npm ci
      - name: Install Playwright
        run: cd ./packages/web-components && npx playwright install --with-deps
      - name: Run tests
        run: cd ./packages/web-components && npm run test.ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/web-components/playwright-report/
          retention-days: 30
