name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm ci
        working-directory: ./packages/web-components
      - name: Install Playwright Dependencies
        run: npx playwright install && npx playwright install-deps
        shell: bash
        working-directory: ./packages/web-components
      - name: Build
        run: npm run build.stencil
        working-directory: ./packages/web-components
      - name: Run Tests
        run: npm run test.ci
        working-directory: ./packages/web-components
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/web-components/playwright-report/
          retention-days: 30
