name: Pull Request Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./packages/web-components/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm run web-comps.install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - run: npm run build.web-comps
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./packages/web-components/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Test
        run: npm run test.web-comps.unit
  e2e-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./packages/web-components/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Test
        run: cd ./packages/web-components && npm run start.stencil && npm run test.e2e
