name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: cd ./packages/web-components && npm ci
      - name: Build
        run: cd ./packages/web-components && npm run build.stencil
      - name: Run tests
        run: cd ./packages/web-components && npm run test.ci
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/web-components/playwright-report/
          retention-days: 30
