name: Pull Request Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Modules
        run: npm ci

      - name: Build
        run: npm run build
  test-components:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test.web-components
  test-react:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test.react
