name: Pull Request Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Modules
        run: npm ci

      - name: Build
        run: npm run build.tests

      - name: Test Components
        run: npm run test.web-components

      - name: Test React
        run: npm run test.react

  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "16"

      - name: Commit Lint
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }}
