name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: cd ./packages/web-components && npm ci
      - name: Build
        run: cd ./packages/web-components && npm run build.stencil
      - name: Run Tests
        run: cd ./packages/web-components && npm run start.test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/web-components/playwright-report/
          retention-days: 30
