name: Pull Request Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Modules
        run: npm ci

      - name: Build
        run: npm run build.tests

      - name: Test Components
        run: npm run test.web-components

      - name: Test React
        run: npm run test.react

      - name: Commit Lint
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }}
