name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    types: [review_requested, ready_for_review]
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: ./packages/web-components/node_modules
          key: ${{ runner.os }}-setup-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./packages/web-components
      - name: Build
        run: npm run build.stencil
        working-directory: ./packages/web-components
  e2e:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ./packages/web-components/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install -D @playwright/test
        working-directory: ./packages/web-components

      - name: e2e Tests
        run: npm run test.cr
        working-directory: ./packages/web-components
