name: Pull Request Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Modules
        run: npm run web-comps.install

      - name: Build
        run: npm run build.web-comps

      - name: Test
        run: npm run test.web-comps.unit && npm run test.web-comps.e2e
