name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json') }}
      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        name: Install Dependencies
        run: npm ci && npx playwright install --with-deps
        working-directory: ./packages/web-components
      - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        name: Build
        run: npm run build.stencil
        working-directory: ./packages/web-components
  e2e:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - name: Get Cache
        uses: actions/cache@v3
        id: get-cache
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json') }}
      - name: e2e Tests
        run: npm run test.ci
        working-directory: ./packages/web-components
  VRTs:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v2
      - name: Get Cache
        uses: actions/cache@v3
        id: get-cache
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json') }}
      - name: Run VRTs
        run: npm run test.vrt
        working-directory: ./packages/web-components
